### ISSUE TITLE
[user expression] invalid expression, but works in field calc

### ISSUE THREAD

**Issue by pigreco** [pigreco/BlobImageSL#1]
the following script
```python
from qgis.core import *
from qgis.gui import *

@qgsfunction(args='auto', group='Custom', handlesnull=True)
def blobjpg_to_html(blob,style,feature,parent):
    """
    Restituisce il blob (che deve essere un jpeg) convertito in HTML img data url per visualizzarlo
    <br> in un Widget HTML o in un suggerimento mappa.
    <br>E' obbligatorio il secondo parametro style. 
    <br>Il parametro style puo assumere il valore '' per nessuno stile (dimensioni originali) 
    <br>o può essere una stringa CSS di stile per img HTML tag,
    <br>Se stile è 'Null' viene applicato di default 'style="max-width:100%; max-height:100%;'.
    <p style="color:Olive"><b>Sintassi</b></p>
    <p style="color:blue"><b>blobjpg_to_html</b><mark style="color:black">(</mark>
    <mark style="color:red">blob</mark><mark style="color:black">,</mark><mark style="color:red">style</mark><mark style="color:black">)</mark>
    <p style="color:Olive"><b>Argomenti</b></p>
    <p style="color:red"><b>blob  </b><mark style="color:black"> - campo contenente i dati blob</mark><br>
    <mark style="color:red"><b>style </b><mark style="color:black"> - campo contenente stringa CSS</mark>
    <p style="color:Olive"><b>Esempi</b></p>
        <ul>
            <li><mark><i> blobjpg_to_html("photo", '') -> tag img con immagine a risoluzione originale</mark></li>
            <li><mark><i> blobjpg_to_html("photo", Null) -> tag img con dimensioni massime </mark></li>
            <li><mark><i> blobjpg_to_html("photo", 'width="250" height="250"')   -> tag img dimensionato</mark></li>
        </ul>
    
    Tratto da https://gis.stackexchange.com/questions/350541/display-photo-stored-as-blob-in-gpkg
    """
    blob64 = blob.toBase64().data().decode()
    if style is None:
        stylestring = 'style="max-width:100%; max-height:100%;"'
    elif not(style):
        stylestring = 'style=""'
    else:
        stylestring = 'style="' + style + '"'
    fullstring = '<img src="data:image/jpeg;base64,' + blob64 + '" ' + stylestring + ' alt="Invalid jpeg">'
    return fullstring
```
error
```
2020-08-27T12:00:38     WARNING    L'espressione utente blob_foto non è valida
             Traceback (most recent call last):
              File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\user.py", line 46, in load_user_expressions
              __import__("expressions.{0}".format(name), locals(), globals())
              File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 794, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python\expressions\blob_foto.py", line 27
              """
              ^
             SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xf2 in position 316: invalid continuation byte
```

this error does not allow me to reload the function the next time QGIS is started, i.e. I cannot find the function in the custom group

## OSGeo4W64 win 10 QGIS master

Chi ci puo' dare una mano??
@slarosa
@agiudiceandrea

**Comment by agiudiceandrea** [comment]
Ciao Salvatore, molto probabilmente il file blob_photo.py è stato salvato con la codifica c,d, ANSI (= Windows-1252), mentre evidentemente il parser si aspetta che sia in UTF-8: siccome in esso sono presenti dei caratteri al di fuori della teballa ASCII (i carattesi "ò" e "è") questo crea un problema nella decodifica.

Quindi, o salvi il file con codifica UTF-8 oppure elimini i caratteri "ò" e "è".

**Comment by pigreco** [comment]
grazie @agiudiceandrea 

## EDIT: SCUSAMI  errore mio, ora funziona!!!

> Quindi, o salvi il file con codifica UTF-8 oppure elimini i caratteri "ò" e "è".

il file usato NON era in UTF-8, ho corretto i caratteri speciali ~~ma nulla ho sempre errore:~~

https://github.com/pigreco/BlobImageSL/commit/a85d201014416d566bc4250b192f3f8a331cd6df#diff-2fc6db92b4e398412068a408dbb0578c

```
2020-08-27T13:54:22     WARNING    L'espressione utente blob_foto non è valida
             Traceback (most recent call last):
              File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\user.py", line 46, in load_user_expressions
              __import__("expressions.{0}".format(name), locals(), globals())
              File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 794, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python\expressions\blob_foto.py", line 27
              """
              ^
             SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xf2 in position 317: invalid continuation byte
```

**Comment by agiudiceandrea** [comment]
Come hai risolto? Hai salvato con la codifica UTF-8 o hai eliminato i caratteri accentati?

**Comment by pigreco** [comment]
> Come hai risolto? Hai salvato con la codifica UTF-8 o hai eliminato i caratteri accentati?

Ho salvato in UTF-8 e per sicurezza ho tolto i caratteri accentati; inoltre avevo il fine riga Windows e non Unix.

grazie, sono queste piccoli dettagli che mi fregano spesso. :-)
